---
title: "Medidas de tendência central e dispersão"
author: "Jairo Nicolau"
date: "13/03/2022"
output: html_document
---

```{r}
library(tidyverse)
library(here)

```

## Banco do Rio de Janeiro

```{r}
library(readxl) # para ler arquivos excel

#library(here) # para ler dados nas pastas

#df <- read_excel(here("dados_originais","bairro_rio_2008.xlsx"))

df <- read_excel("bairro_rio_2008.xlsx")

```

```{r}
glimpse(df)
```

#### selecionando as variaveis importantes

```{r}
bairro <- df %>% 
  select(Bairro_IPP, GPP, RegAdmin, Dom, DomFav, Pop2000, PopF,PopM, RDom_Media, Rlg_CAR, Rlg_EMis_pc,Rlg_EPtc_pc, AEstu_Media)

glimpse(bairro)
```


#### criando variáveis


```{r}
bairro %>% 
mutate(pct_favela = DomFav/ Dom,
       pct_evangelico = Rlg_EMis_pc + Rlg_EPtc_pc) -> bairro 
```


#### salvando o banco

```{r}
#library(readr)
write_csv(bairro, "bairros_rio.csv")

```




## Começão de um banco criado


```{r}
df2 <- read_csv(here("bairros_rio.csv"))
```



### Fazendo sinteses

```{r}
bairro %>% 
  group_by(GPP) %>%
  summarize(total_bairros = n(),
            media_favela = mean (pct_favela)*100,
            mediana_evangelico = median(pct_evangelico),
            desvio_favela = sd(pct_favela),
            total_pop = sum (Pop2000)) -> SUMARIO 
  
  
```







#### Sumário de 5 Números


```{r}
bairro %>% 
  summarize( n = n(), 
             Min = min(pct_favela),
             Q1 = quantile(pct_favela, .25),
             Media = mean(pct_favela), 
             Q3 = quantile(pct_favela, .75),
             Max = max(pct_favela)
             )
```

```{r}
bairro %>% 
  summary
```



```{r}
bairro %>% 
select(pct_favela) %>%
  summary()
```

### Encontrando quantis específicos

```{r}
bairro %>% 
  summarize( 
             bottom_10 = quantile(pct_evangelico, .10),
             mediana = mean(pct_favela), 
             top_25 = quantile(pct_evangelico, .75),
             top_1 = quantile(pct_evangelico, .99)
             )
```


#### Calculando o z-score

```{r}
mean(bairro$pct_favela)
```

```{r}
sd(bairro$pct_favela)
```

```{r}
bairro %>% 
  mutate(zscore = (pct_favela- mean(pct_favela))/sd(pct_favela)) ->bairro
```

```{r}
ggplot(bairro, aes(zscore)) +
  geom_histogram()
```




